# Generated by Django 5.0.4 on 2024-08-14 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupTodo',
            fields=[
                ('id_groupTodo', models.IntegerField(primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GroupTodoUser',
            fields=[
                ('id_TodoUser', models.IntegerField(primary_key=True, serialize=False)),
                ('idGroupTodo', models.ForeignKey(db_column='id_groupTodo', null=True, on_delete=django.db.models.deletion.RESTRICT, to='mainApp.grouptodo')),
            ],
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Description', models.TextField(null=True)),
                ('Date', models.DateField(null=True)),
                ('Completed', models.BooleanField(default=False)),
                ('User', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idGroupTodo', models.ForeignKey(db_column='id_groupTodo', null=True, on_delete=django.db.models.deletion.RESTRICT, to='mainApp.grouptodo')),
            ],
        ),
    ]
