# Generated by Django 5.0.4 on 2024-08-15 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouptodo',
            name='id_groupTodo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='grouptodouser',
            name='id_TodoUser',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='idGroupTodo',
            field=models.ForeignKey(blank=True, db_column='id_groupTodo', null=True, on_delete=django.db.models.deletion.RESTRICT, to='mainApp.grouptodo'),
        ),
    ]
