# Generated by Django 5.0.4 on 2024-09-07 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_rename_user_grouptodouser_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grouptodouser',
            old_name='Userid',
            new_name='User',
        ),
    ]
